#!/usr/bin/env bash

ZUI_STORE="${SNAP_COMMON}/zui-store"

if [ ! -d "${ZUI_STORE}" ]; then
	echo "Missing store-dir for ZUI. Failed, exiting...." >&2
	exit 1
fi

if [ $(ls "${ZUI_STORE}" | wc -l) -eq 0 ]; then
	cpy_2_zui && sudo snap stop "${SNAP_NAME}" && sudo snap disable "${SNAP_NAME}"
fi
