#!/usr/bin/env bash

export DAEMONIZED=1
source $SNAP/helper/functions

RAND="$(snapctl get -d session.secret)"
snapctl set :zui-store transfer="${RAND}"
lprint "Secret: ${RAND}"

SNAP_CONFIG="$(snapctl get -d server mqtt session transfer)"
snapctl set :zui-store z2mconfig="${SNAP_CONFIG}"
lprint "Export snap config over plug connection: ${SNAP_CONFIG}" 

USING_SERIAL="$(snapctl is-connected serial-port && echo 1 || echo 0)"
snapctl set :zui-store z2mserial="${USING_SERIAL}"

lprint "Share serial-port plug be used (${USING_SERIAL}) over plug connection."
